### ISSUE TITLE
string format in czech locale

### ISSUE THREAD

**Issue by bklabs** [jcheng31/ForecastPCL#5]
Hi
I've faced with problem with decimal separator in  czech locale - it is a "," but not "."
So, as result, "https://api.forecast.io/forecast/{0}/{1},{2}?units={3}&extend={4}&exclude={5}&lang={6}" will be formatted as "https://api.forecast.io/forecast/APIKEY/50,029,14,49?units=....."

workaround for now:

 CultureInfo ci = Thread.CurrentThread.CurrentCulture;
 Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
 _forecast = await _forecastClient.GetWeatherDataAsync(_lat, _longt, units, language);
 Thread.CurrentThread.CurrentCulture = ci;

Regards 
Dmitry Belov

**Comment by jcheng31** [comment]
Hey, thanks for reporting this. I'm looking into it now, and should be able to get a fix out soon - it looks like a fairly easy change, so it shouldn't take too long :)

**Comment by jcheng31** [comment]
All right, I think that should fix it. I've published the change to NuGet, so you should be able to update through there - let me know if the issue's still there!

**Comment by bklabs** [comment]
Hi

GetWeatherDataAsync still does not work in Czech locale (

Regards

Dmitry Belov

**Comment by bklabs** [comment]
BTW

You can send a Culture directly as an argument in to string.Format method

Regards 

D.

**Comment by jcheng31** [comment]
Oops, I updated the time machine method but not the "main" one - my bad. I'll get to it in a bit.

**Comment by jcheng31** [comment]
Alright, just made the change, added some simple tests, and published it. Let me know if it works :)

**Comment by bklabs** [comment]
Hi

It works! Thank you.

Regards

D.

**Comment by jcheng31** [comment]
No problem :)
